application: beautybible2013
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:



- url: /images
  static_dir: images

- url: /js
  static_dir: js

# Twitter Bootstrap
- url: /css
  static_dir: css

# Handler for front page
- url: /
  script: front.app

# All other pages require login
- url: /.*
  script: beautybible.app
  login: required

libraries:
- name: jinja2
  version: latest